export const

  CONFIG_LIST_FETCH = 'CONFIG_LIST_FETCH',
  CONFIG_LIST_FETCH_PENDING = 'CONFIG_LIST_FETCH_PENDING',
  CONFIG_LIST_FETCH_FULFILLED = 'CONFIG_LIST_FETCH_FULFILLED',
  CONFIG_LIST_FETCH_REJECTED = 'FETCH_LYRICS_REJECTED',

  CONFIG_DEFINITION_FETCH = 'CONFIG_DEFINITION_FETCH',
  CONFIG_DEFINITION_FETCH_PENDING = 'CONFIG_DEFINITION_FETCH_PENDING',
  CONFIG_DEFINITION_FETCH_FULFILLED = 'CONFIG_DEFINITION_FETCH_FULFILLED',
  CONFIG_DEFINITION_FETCH_REJECTED = 'FETCH_LYRICS_REJECTED',

  CONFIG_DEFINITION_SAVE = 'CONFIG_DEFINITION_SAVE',
  CONFIG_DEFINITION_SAVE_PENDING = 'CONFIG_DEFINITION_SAVE_PENDING',
  CONFIG_DEFINITION_SAVE_FULFILLED = 'CONFIG_DEFINITION_SAVE_FULFILLED',
  CONFIG_DEFINITION_SAVE_REJECTED = 'SAVE_LYRICS_REJECTED',

  CONFIG_PROJECT_UPDATE = 'CONFIG_PROJECT_UPDATE',
  CONFIG_VARIABLE_UPDATE = 'CONFIG_VARIABLE_UPDATE',
  CONFIG_VARIABLE_SELECT = 'CONFIG_VARIABLE_SELECT',
  CONFIG_VARIABLE_DESELECT = 'CONFIG_VARIABLE_DESELECT'
