export const
  CONFIG_LIST_FETCH = 'CONFIG_LIST_FETCH',
  CONFIG_LIST_FETCH_PENDING = 'CONFIG_LIST_FETCH_PENDING',
  CONFIG_LIST_FETCH_FULFILLED = 'CONFIG_LIST_FETCH_FULFILLED',
  CONFIG_LIST_FETCH_REJECTED = 'FETCH_LYRICS_REJECTED',
  CONFIG_DEFINITION_FETCH = 'CONFIG_DEFINITION_FETCH',
  CONFIG_DEFINITION_FETCH_PENDING = 'CONFIG_DEFINITION_FETCH_PENDING',
  CONFIG_DEFINITION_FETCH_FULFILLED = 'CONFIG_DEFINITION_FETCH_FULFILLED',
  CONFIG_DEFINITION_FETCH_REJECTED = 'FETCH_LYRICS_REJECTED'
